{
  "debianbug": 948224,
  "description": "There is a DoS vulnerability in Pillow before 6.2.2 caused by FpxImagePlugin.py calling the range function on an unvalidated 32-bit integer if the number of bands is large. On Windows running 32-bit Python, this results in an OverflowError or MemoryError due to the 2 GB limit. However, on Linux running 64-bit Python this results in the process being terminated by the OOM killer.",
  "releases": {
    "bullseye": {
      "fixed_version": "7.0.0-1",
      "repositories": {
        "bullseye": "8.1.2+dfsg-0.1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "5.4.1-2+deb10u1",
      "repositories": {
        "buster": "5.4.1-2+deb10u2",
        "buster-security": "5.4.1-2+deb10u1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "7.0.0-1",
      "repositories": {
        "sid": "8.1.2+dfsg-0.1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "4.0.0-4+deb9u1",
      "repositories": {
        "stretch": "4.0.0-4+deb9u1",
        "stretch-security": "4.0.0-4+deb9u2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}