{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2020-36226",
  "PublicDate": "2021-01-26T18:15:00Z",
  "References": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36226"
  ],
  "Description": "A flaw was discovered in OpenLDAP before 2.4.57 leading to a memch-\u003ebv_len miscalculation and slapd crash in the saslAuthzTo processing, resulting in denial of service.",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": [
    "https://bugs.openldap.org/show_bug.cgi?id=9413"
  ],
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "mdeslaur",
  "Patches": {
    "openldap": {
      "bionic": {
        "Status": "needed",
        "Note": ""
      },
      "devel": {
        "Status": "needed",
        "Note": ""
      },
      "focal": {
        "Status": "needed",
        "Note": ""
      },
      "groovy": {
        "Status": "needed",
        "Note": ""
      },
      "precise/esm": {
        "Status": "needed",
        "Note": ""
      },
      "trusty": {
        "Status": "ignored",
        "Note": "out of standard support"
      },
      "trusty/esm": {
        "Status": "needed",
        "Note": ""
      },
      "upstream": {
        "Status": "released",
        "Note": "2.4.57+dfsg-1"
      },
      "xenial": {
        "Status": "needed",
        "Note": ""
      }
    }
  },
  "UpstreamLinks": {
    "openldap": [
      "https://git.openldap.org/openldap/openldap/-/commit/d169e7958a3e0dc70f59c8374bf8a59833b7bdd8"
    ]
  }
}