{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2020-36222",
  "PublicDate": "2021-01-26T18:15:00Z",
  "References": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36222"
  ],
  "Description": "A flaw was discovered in OpenLDAP before 2.4.57 leading to an assertion failure in slapd in the saslAuthzTo validation, resulting in denial of service.",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": [
    "https://bugs.openldap.org/show_bug.cgi?id=9406",
    "https://bugs.openldap.org/show_bug.cgi?id=9407"
  ],
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "mdeslaur",
  "Patches": {
    "openldap": {
      "bionic": {
        "Status": "needed",
        "Note": ""
      },
      "devel": {
        "Status": "needed",
        "Note": ""
      },
      "focal": {
        "Status": "needed",
        "Note": ""
      },
      "groovy": {
        "Status": "needed",
        "Note": ""
      },
      "precise/esm": {
        "Status": "needed",
        "Note": ""
      },
      "trusty": {
        "Status": "ignored",
        "Note": "out of standard support"
      },
      "trusty/esm": {
        "Status": "needed",
        "Note": ""
      },
      "upstream": {
        "Status": "released",
        "Note": "2.4.57+dfsg-1"
      },
      "xenial": {
        "Status": "needed",
        "Note": ""
      }
    }
  },
  "UpstreamLinks": {
    "openldap": [
      "https://git.openldap.org/openldap/openldap/-/commit/6ed057b5b728b50746c869bcc9c1f85d0bbbf6ed",
      "https://git.openldap.org/openldap/openldap/-/commit/02dfc32d658fadc25e4040f78e36592f6e1e1ca0"
    ]
  }
}