{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2021-3520",
  "PublicDate": "2021-04-30T00:00:00Z",
  "References": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3520",
    "https://github.com/lz4/lz4/pull/972"
  ],
  "Description": "memory corruption due to an integer overflow bug caused by memmove argument",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": [
    "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987856"
  ],
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "mdeslaur",
  "Patches": {
    "lz4": {
      "bionic": {
        "Status": "needed",
        "Note": ""
      },
      "devel": {
        "Status": "not-affected",
        "Note": "1.9.3-2"
      },
      "esm-infra/xenial": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "needed",
        "Note": ""
      },
      "groovy": {
        "Status": "needed",
        "Note": ""
      },
      "hirsute": {
        "Status": "needed",
        "Note": ""
      },
      "precise/esm": {
        "Status": "DNE",
        "Note": ""
      },
      "trusty": {
        "Status": "ignored",
        "Note": "out of standard support"
      },
      "trusty/esm": {
        "Status": "needs-triage",
        "Note": ""
      },
      "upstream": {
        "Status": "released",
        "Note": "1.9.3-2"
      },
      "xenial": {
        "Status": "ignored",
        "Note": "end of standard support, was needs-triage"
      }
    }
  },
  "UpstreamLinks": {
    "lz4": [
      "https://github.com/lz4/lz4/commit/8301a21773ef61656225e264f4f06ae14462bca7"
    ]
  }
}