{
  "debianbug": 986791,
  "description": "A flaw was found in PoDoFo 0.9.7. An use-after-free in PoDoFo::PdfVecObjects::Clear() function can cause a denial of service via a crafted PDF file.",
  "releases": {
    "bullseye": {
      "nodsa": "Minor issue",
      "nodsa_reason": "",
      "repositories": {
        "bullseye": "0.9.7+dfsg-2"
      },
      "status": "open",
      "urgency": "not yet assigned"
    },
    "buster": {
      "nodsa": "Minor issue",
      "nodsa_reason": "",
      "repositories": {
        "buster": "0.9.6+dfsg-5"
      },
      "status": "open",
      "urgency": "not yet assigned"
    },
    "sid": {
      "repositories": {
        "sid": "0.9.7+dfsg-2"
      },
      "status": "open",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "nodsa": "Minor issue; can be fixed in next update",
      "nodsa_reason": "postponed",
      "repositories": {
        "stretch": "0.9.4-6"
      },
      "status": "open",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}