{
  "description": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause a use-after-free in ext4_xattr_set_entry function and a denial of service or unspecified other impact may occur by renaming a file in a crafted ext4 filesystem image.",
  "releases": {
    "bullseye": {
      "fixed_version": "4.17.3-1",
      "repositories": {
        "bullseye": "5.10.24-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "4.17.3-1",
      "repositories": {
        "buster": "4.19.171-2",
        "buster-security": "4.19.171-2"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "4.17.3-1",
      "repositories": {
        "sid": "5.10.24-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "4.9.110-1",
      "repositories": {
        "stretch": "4.9.228-1",
        "stretch-security": "4.9.258-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}