{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "apache-commons-io",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "javapackages-tools:201801/apache-commons-io",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "maven:3.5/apache-commons-io",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "maven:3.6/apache-commons-io",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Under investigation",
      "package_name": "rh-maven36-apache-commons-io",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2021-04-12T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2021-29425 apache-commons-io: Limited path traversal in Apache Commons IO 2.2 to 2.6",
    "id": "1948752",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1948752"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:H/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-22",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2021-29425",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}