{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat OpenStack Platform 10 (Newton)",
      "fix_state": "Under investigation",
      "package_name": "puppet",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Under investigation",
      "package_name": "puppet",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 15 (Stein)",
      "fix_state": "Under investigation",
      "package_name": "puppet",
      "cpe": "cpe:/a:redhat:openstack:15"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Under investigation",
      "package_name": "puppet",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Affected",
      "package_name": "puppet-agent",
      "cpe": "cpe:/a:redhat:network_satellite:6"
    },
    {
      "product_name": "Red Hat Update Infrastructure 3 for Cloud Providers",
      "fix_state": "Under investigation",
      "package_name": "puppet",
      "cpe": "cpe:/a:redhat:rhui:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2021-02-10T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2021-27017 puppet-agent: Deserialization of untrusted data",
    "id": "1927502",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1927502"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.6",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-502",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2021-27017",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}